name: festitrack
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  firebase_core: any
  firebase_auth: any
  google_sign_in: any
  google_maps_flutter: any
  geolocator: any
  cloud_firestore: any
  intl: any
  google_sign_in_ios: ^5.7.6
  permission_handler: ^11.3.1
  uuid: ^4.4.0
  firebase_dynamic_links: ^6.0.2
  share_plus: ^9.0.0
  location: ^7.0.0
  provider: ^6.1.2
  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
